Proceso EDAD_PERSONA

	DEFINIR AÑO_NACIMIENTO, AÑO_ACTUAL COMO ENTERO; 
	DEFINIR EDAD COMO ENTERO;
	ESCRIBIR " INGRESE EL AÑO DE NACIMIENTO"; 
	LEER AÑO_NACIMIENTO; 
	ESCRIBIR "INGRESE EL AÑO ACTUAL"; 
	LEER AÑO_ACTUAL; 
	EDAD = AÑO_ACTUAL - AÑO_NACIMIENTO; 
	ESCRIBIR "LA EDAD DE LA PERSONA ES:", EDAD, "AÑOS";
	
FinProceso
